apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app: deltahouse

resources:
#  - pv-database.yaml
#  - database.yaml
  - service.yaml
  - deploy-backend.yaml
  - deploy-frontend.yaml
#  - http-route.yaml
  - ingress-route.yaml

#configMapGenerator:
#  - name: configuration
#    files:
#      - configuration.yaml
